# === GitHub username to Full name map ===
#
# trotyl   - Zejiang Yu
# futantan - Tantan Fu
# klxq     - Ling Wang
# ndrlslz  - Xu Yao

version: 2

always_pending:
  title_regex: 'WIP'
  explanation: 'Work in progress...'

group_defaults:
  required: 1
  reset_on_reopened:
    enabled: true
  reset_on_push:
    enabled: true
  approve_by_comment:
    enabled: true
    approve_regex: '^LGTM'

groups:
  build-and-ci:
    users:
      - trotyl

    conditions:
      branches:
        - master

      files:
        include:
          - "*.yml"
          - "*.json"
          - "*.lock"
          - "*.md"

  main:
    required: 2
    
    users:
      - trotyl
      - futantan
      - klxq
      - ndrlslz

    conditions:
      branches:
        - master

      files:
        include:
          - "src/*"
